// Bilingual content store — full real data from source documents.
// 12 national competitions + Tamil Nadu state-level context.

// Site-wide freshness — the date we last cross-checked everything against
// official portals. Bump this when you re-verify.
const LAST_VERIFIED = '2026-04-15';   // ISO

const COPY = {
  brand: {
    ta: 'அறிவியல் போட்டி',
    en: 'Ariviyal Poatti',
  },
  tagline: {
    ta: 'இந்தியாவின் பள்ளி அளவிலான அறிவியல் போட்டிகளின் தெளிவான வழிகாட்டி — தமிழ்நாட்டிற்கு.',
    en: 'A clear guide to India\u2019s school-level science competitions — focused on Tamil Nadu.',
  },
  nav: {
    home:         { ta: 'முகப்பு',          en: 'Home' },
    competitions: { ta: 'போட்டிகள்',        en: 'Competitions' },
    dates:        { ta: 'முக்கிய தேதிகள்',  en: 'Key Dates' },
    start:        { ta: 'இங்கே தொடங்குங்கள்', en: 'Start Here' },
    about:        { ta: 'இது ஏன் இருக்கிறது', en: 'Why This Exists' },
  },
  home: {
    heroKicker:    { ta: '12 தேசிய போட்டிகள் · தமிழ்நாட்டிற்கு ஒரே இடத்தில்', en: '12 national competitions · curated for Tamil Nadu' },
    heroTitle: {
      ta: 'பள்ளி மாணவர்களுக்கான அறிவியல் போட்டிகள் — தேடல் இனி எளிது.',
      en: 'School science competitions — finally, in one place.',
    },
    heroSub: {
      ta: 'இந்தியாவில் 14.72 லட்சம் பள்ளிகள், 12 முக்கிய போட்டிகள், ஒவ்வொன்றும் வெவ்வேறு தேதி, தகுதி, நடைமுறை. இங்கே அனைத்தையும் தெளிவாக தொகுத்துள்ளோம்.',
      en: '14.72 lakh schools, 12 major competitions, each with its own dates, eligibility, and process. All gathered here — honestly, without fluff.',
    },
    audiencePrompt: { ta: 'நீங்கள் யார்?', en: 'Who are you?' },
    deadlineKicker: { ta: 'அடுத்த முக்கியமான தேதி', en: 'Next important deadline' },
    urgencyHeadline: {
      ta: 'INSPIRE–MANAK யோசனை சமர்ப்பணம் — செப்டம்பர் கடைசி வரை',
      en: 'INSPIRE\u2013MANAK idea submissions — open till late September',
    },
    urgencyAction:   { ta: 'விவரங்களைப் பார்', en: 'See details' },
    ctaSeeAll:       { ta: '12 போட்டிகளையும் பார்', en: 'Browse all 12 competitions' },
    ctaSeeDates:     { ta: 'வருடாந்திர காலண்டர்',  en: 'See annual calendar' },
    sectionCompetitions: { ta: 'இப்போது நடக்கும் போட்டிகள்', en: 'Active right now' },
    sectionCompetitionsSub: { ta: '2025–26 கல்வியாண்டு · ஜூன் → மே', en: '2025\u201326 academic year \u00b7 Jun \u2013 May' },
    footerNote: { ta: 'இது ஒரு அரசு தளம் அல்ல. சரிபார்ப்புக்கு எப்போதும் அதிகாரப்பூர்வ மூலத்தைப் பார்க்கவும்.', en: 'This is not a government site. Always verify with the official source.' },
  },
  audiences: {
    teacher: {
      label:   { ta: 'ஆசிரியர்',  en: 'Teacher' },
      line:    { ta: 'இந்த வாரம் என்ன செய்ய வேண்டும்', en: 'What to do this week' },
      detail:  { ta: 'உங்கள் மாணவர்களுக்கான படிவங்கள், காலக்கெடுகள், படிநிலை செயல்கள்.',
                 en: 'Forms, deadlines, and step-by-step actions for your class.' },
    },
    principal: {
      label:   { ta: 'முதல்வர்',  en: 'Principal' },
      line:    { ta: 'பள்ளிக்கு மதிப்புள்ளதா',       en: 'Is this worth the school\u2019s time' },
      detail:  { ta: 'பங்கேற்பின் விளைவுகள், முந்தைய வெற்றிகள், தேவையான ஆதாரங்கள்.',
                 en: 'Outcomes, past results, resources your school will need.' },
    },
    parent: {
      label:   { ta: 'பெற்றோர்',  en: 'Parent' },
      line:    { ta: 'என் குழந்தைக்கு என்ன வாய்ப்புகள்', en: 'Opportunities for my child' },
      detail:  { ta: 'உங்கள் குழந்தையின் வயதுக்குப் பொருத்தமான போட்டிகள், பயன்கள், எப்படி ஆதரவளிக்கலாம்.',
                 en: 'Age-appropriate competitions, benefits, and how to support them.' },
    },
  },
  startHere: {
    title: { ta: 'உங்கள் வழி', en: 'Your path' },
    intro: { ta: 'ஒரு பாத்திரத்தைத் தேர்ந்தெடுங்கள். அடுத்த படி சொல்கிறோம்.', en: 'Pick a role. We\u2019ll tell you the next step.' },
    teacher: [
      { ta: 'உங்கள் பள்ளியில் INSPIRE நோடல் ஆசிரியர் அல்லது SCERT தொடர்பாளர் இருக்கிறாரா எனப் பார்க்கவும்.', en: 'Check whether your school has an INSPIRE nodal teacher or SCERT contact.' },
      { ta: 'ஒரே ஒரு போட்டியைத் தேர்ந்தெடுங்கள் — INSPIRE–MANAK எளிதாகத் தொடங்கலாம், முற்றிலும் இலவசம்.', en: 'Pick one competition to start. INSPIRE\u2013MANAK is the easiest on-ramp \u2014 zero fee, zero infrastructure.' },
      { ta: 'உங்கள் வகுப்பில் இருந்து 5 மாணவர்களை நாமினேட் செய்யுங்கள் — ஆண்டுக்கு 10 லட்சம் யோசனைகள் இலக்கு.', en: 'Nominate 5 students from your class \u2014 the national target is 10 lakh ideas a year.' },
      { ta: 'இந்த பக்கத்தை WhatsApp-ல் சக ஆசிரியர்களுக்கு அனுப்புங்கள்.', en: 'Share this page with fellow teachers on WhatsApp.' },
      { ta: 'நவம்பர்–ஜனவரி நெரிசலான காலம் — உங்கள் மாணவர்கள் ஒரு வாரம் முன்னதாக தயாராக உதவுங்கள்.', en: 'November\u2013January is the crowded window \u2014 help your students prepare a week ahead.' },
    ],
    principal: [
      { ta: 'உங்கள் பள்ளியின் கடந்த ஆண்டு பங்கேற்பை மதிப்பிடுங்கள் — INSPIRE, RBVP, NCSC எவற்றிலாவது பதிவு செய்யப்பட்டதா?', en: 'Review last year\u2019s record \u2014 did your school register for INSPIRE, RBVP, or NCSC?' },
      { ta: 'ஒரு ஆசிரியரை அறிவியல் போட்டிகளுக்கான ஒருங்கிணைப்பாளராக நியமிக்கவும். ஒரு நபர், ஒரு பொறுப்பு.', en: 'Appoint one teacher as Science Competitions Coordinator. One person, one mandate.' },
      { ta: 'ATL ஆய்வகம் இருந்தால், ATL Marathon-ல் குழுவை பதிவு செய்யுங்கள் — அரசு ஆதரவு உள்ளது.', en: 'If you have an Atal Tinkering Lab, register a team for the ATL Marathon \u2014 it is fully government-backed.' },
      { ta: 'நவம்பர்–ஜனவரி போட்டிகள் மோதக்கூடும். பள்ளி கேலெண்டரில் முன்கூட்டியே குறிக்கவும்.', en: 'November\u2013January collision zone is real. Pencil dates into the school calendar early.' },
      { ta: 'வெற்றி பெறும் மாணவர்களை பள்ளியின் முன்வெளியில் கௌரவியுங்கள் — அடுத்த ஆண்டு பல மடங்கு மாணவர்கள் முயற்சி செய்வார்கள்.', en: 'Celebrate winners publicly at school \u2014 the next year sees many more students try.' },
    ],
    parent: [
      { ta: 'உங்கள் குழந்தையின் வகுப்பிற்கு பொருத்தமான போட்டிகளை வடிகட்டுங்கள் — 1ம் வகுப்பில் கூட Olympiads உள்ளன.', en: 'Filter by class \u2014 there are Olympiads even for Class 1 students.' },
      { ta: 'பள்ளி ஒருங்கிணைப்பாளரிடம் சமர்ப்பிக்க ஒரு குறிப்பை எழுதிக் கொள்ளுங்கள். பள்ளி வழியாகத்தான் பதிவு நடக்கிறது.', en: 'Write a short note for the school coordinator \u2014 most registrations happen only through the school.' },
      { ta: 'செலவு தடை உள்ளதா என்று சரிபார்க்கவும் — INSPIRE, RBVP, NCSC முற்றிலும் இலவசம். WRO, FLL விலை அதிகம்.', en: 'Check the fee \u2014 INSPIRE, RBVP, NCSC are free. WRO and FLL carry real cost barriers.' },
      { ta: 'முந்தைய ஆண்டு கேள்வித்தாள்களை இலவசமாக பயிற்சி செய்யுங்கள்.', en: 'Practice with past-year papers \u2014 they are free online.' },
      { ta: 'ஒரு வெற்றியும், ஒரு தோல்வியும் — இரண்டும் மதிப்புள்ளவை என்பதை சொல்லுங்கள். போட்டியின் முயற்சி முக்கியம்.', en: 'Remind them: a win and a loss both matter. The attempt is what counts.' },
    ],
  },
  dates: {
    title: { ta: 'முக்கிய தேதிகள்', en: 'Key Dates' },
    sub:   { ta: '2025–26 கல்வியாண்டு · 12 போட்டிகளின் வருடாந்திர காலண்டர். WhatsApp-ல் பகிரலாம்.',
             en: '2025\u201326 academic year \u00b7 annual calendar of all 12 competitions. Share on WhatsApp.' },
    shareWhatsapp: { ta: 'WhatsApp-ல் பகிர்', en: 'Share on WhatsApp' },
    statusOpen:    { ta: 'பதிவு திறந்துள்ளது', en: 'Registration open' },
    statusSoon:    { ta: 'விரைவில் மூடப்படும்', en: 'Closing soon' },
    statusUpcoming:{ ta: 'வரவிருக்கிறது',     en: 'Upcoming' },
    statusClosed:  { ta: 'முடிந்தது',          en: 'Closed' },
    collisionNote: { ta: 'நவம்பர்–ஜனவரி மிக நெரிசலான காலம் — NSE, SOF நிலை 1, CBSE பிராந்திய, IRIS திரையிடல், WRO மற்றும் NCSC அனைத்தும் ஒரே நேரத்தில்.', en: 'November\u2013January is the collision zone \u2014 NSE, SOF Level 1, CBSE regionals, IRIS screening, WRO, and NCSC all converge here.' },
  },
  about: {
    title: { ta: 'இது ஏன் இருக்கிறது', en: 'Why this exists' },
    body: [
      { ta: 'இது ஒரு அரசு தளம் அல்ல. ஒரு NGO-வும் அல்ல. ஒரு தொடக்க நிறுவனமும் அல்ல.',
        en: 'This is not a government portal. Not an NGO. Not a startup.' },
      { ta: 'இந்தியாவில் 14.72 லட்சம் பள்ளிகள், 12 முக்கிய தேசிய அறிவியல் போட்டிகள் உள்ளன. ஆனால் ஒவ்வொரு போட்டியின் தகவலும் வெவ்வேறு தளங்களில் சிதறியுள்ளது.',
        en: 'India has 14.72 lakh schools and 12 major national science competitions. But the information for each is scattered across different sites.' },
      { ta: 'தமிழ்நாட்டில் 57,935 பள்ளிகள். IRIS 2024 தேசிய இறுதி 101 மாணவர்களில் — தமிழ்நாட்டிலிருந்து வெறும் 3 பேர். அவர்கள் மூவரும் சென்னை மற்றும் கோயம்புத்தூரிலுள்ள தனியார் பள்ளிகளில். அரசு பள்ளி மாணவர் ஒருவரும் இல்லை.',
        en: 'Tamil Nadu has 57,935 schools. Out of 101 national IRIS 2024 finalists \u2014 only 3 were from Tamil Nadu, all from private schools in Chennai and Coimbatore. Not a single government school student.' },
      { ta: 'வானவில் மன்றம் 25 லட்சம் அரசு பள்ளி மாணவர்களை சென்றடைகிறது. ஆனால் அது எந்த தேசிய போட்டியுடனும் இணைக்கப்படவில்லை. இது மாற்றப்பட வேண்டும்.',
        en: 'Vaanavil Mandram reaches 25 lakh government school students \u2014 but isn\u2019t connected to any national competition pipeline. That has to change.' },
      { ta: 'எனவே தகவலை ஒரே இடத்தில், இரண்டு மொழிகளில், நேர்மையாக ஒன்று சேர்த்திருக்கிறோம். இது ஒரு நண்பனின் வேலை — ஆராய்ச்சியை முடித்து, தெளிவாக உங்களுக்குத் தருகிறது.',
        en: 'So we put the information in one place, in two languages, honestly. Think of this as a friend who has done the research and laid it out for you clearly.' },
      { ta: 'தவறு இருந்தால் — தயவு செய்து எங்களுக்குத் தெரிவியுங்கள். நாங்கள் திருத்துவோம்.',
        en: 'If something is wrong \u2014 please tell us. We\u2019ll fix it.' },
    ],
    sources: { ta: 'ஆதாரம்',  en: 'Sources' },
    sourcesText: { ta: 'UDISE+ 2023–24, 2024–25 · HBCSE · NCERT · DST · AIM/NITI Aayog · IARCS · TN SEP 2025 · TN பட்ஜெட் 2025–26', en: 'UDISE+ 2023\u201324, 2024\u201325 \u00b7 HBCSE \u00b7 NCERT \u00b7 DST \u00b7 AIM/NITI Aayog \u00b7 IARCS \u00b7 TN SEP 2025 \u00b7 TN Budget 2025\u201326' },
    contact: { ta: 'தொடர்பு',  en: 'Contact' },
    tnTitle: { ta: 'தமிழ்நாடு — எண்களில்', en: 'Tamil Nadu — the numbers' },
    tnFacts: [
      { ta: '57,935 பள்ளிகள் · 1.25 கோடி மாணவர்கள்',  en: '57,935 schools \u00b7 1.25 crore students' },
      { ta: '1,197 INSPIRE தேர்வுகள் (2024–25)',        en: '1,197 INSPIRE selections (2024\u201325)' },
      { ta: 'IRIS 2024: 101-ல் 3 பதிவுகள் மட்டுமே',    en: 'IRIS 2024: only 3 of 101 finalists' },
      { ta: 'வானவில் மன்றம்: 25 லட்சம் மாணவர்கள்',     en: 'Vaanavil Mandram: 25 lakh students' },
    ],
  },
  common: {
    register:     { ta: 'அதிகாரப்பூர்வ தளத்தை பார்', en: 'Go to official site' },
    learnMore:    { ta: 'மேலும் அறிய',      en: 'Learn more' },
    eligibility:  { ta: 'தகுதி',             en: 'Eligibility' },
    deadline:     { ta: 'முக்கிய தேதி',     en: 'Key deadline' },
    process:      { ta: 'நடைமுறை',         en: 'Process' },
    fee:          { ta: 'கட்டணம்',          en: 'Fee' },
    free:         { ta: 'இலவசம்',           en: 'Free' },
    official:     { ta: 'அதிகாரப்பூர்வ இணையதளம்', en: 'Official site' },
    back:         { ta: '← திரும்பு',       en: '← Back' },
    all:          { ta: 'அனைத்தும்',       en: 'All' },
    daysLeft:     { ta: 'நாட்கள் மீதம்',    en: 'days left' },
    organiser:    { ta: 'ஆயோஜகர்',         en: 'Organiser' },
    since:        { ta: 'தொடக்கம்',         en: 'Since' },
    reach:        { ta: 'பள்ளி எட்டுதல்',  en: 'School reach' },
    intlPath:     { ta: 'சர்வதேச பாதை',    en: 'International pathway' },
    schoolType:   { ta: 'பள்ளி வகை',       en: 'School type' },
  },
  categories: {
    all:      { ta: 'அனைத்தும்',   en: 'All' },
    govt:     { ta: 'அரசு',         en: 'Government' },
    ngo:      { ta: 'NGO/Research', en: 'NGO / Research' },
    olympiad: { ta: 'ஒலிம்பியாட்', en: 'Olympiad' },
    private:  { ta: 'தனியார்',     en: 'Private' },
    robotics: { ta: 'ரோபோட்டிக்ஸ்',en: 'Robotics' },
  },
};

// Helper to build a competition entry.
function C(id, cat, status, nameTa, nameEn, shortTa, shortEn, eligibilityTa, eligibilityEn,
          feeTa, feeEn, deadline, deadlineLabelTa, deadlineLabelEn,
          summaryTa, summaryEn, process, official, organiserTa, organiserEn,
          since, reachTa, reachEn, intlTa, intlEn, schoolTypeTa, schoolTypeEn) {
  return {
    id, category: cat, status,
    name: { ta: nameTa, en: nameEn },
    shortName: { ta: shortTa, en: shortEn },
    eligibility: { ta: eligibilityTa, en: eligibilityEn },
    fee: { ta: feeTa, en: feeEn },
    deadline,
    deadlineLabel: { ta: deadlineLabelTa, en: deadlineLabelEn },
    summary: { ta: summaryTa, en: summaryEn },
    process,
    official,
    organiser: { ta: organiserTa, en: organiserEn },
    since,
    reach: { ta: reachTa, en: reachEn },
    intlPath: { ta: intlTa, en: intlEn },
    schoolType: { ta: schoolTypeTa, en: schoolTypeEn },
  };
}

const COMPETITIONS = [
  C('inspire-manak', 'govt', 'open',
    'INSPIRE–MANAK', 'INSPIRE\u2013MANAK',
    'INSPIRE', 'INSPIRE',
    '6–12 வகுப்பு · வயது 10–17', 'Classes 6\u201312 \u00b7 age 10\u201317',
    'இலவசம்', 'Free',
    '2026-09-30', 'யோசனை சமர்ப்பணம்', 'Idea submission',
    'இந்தியாவின் மிகப்பெரிய பள்ளி அளவிலான அறிவியல் புதுமைத் திட்டம். DST மற்றும் NIF நடத்துகிறது. தேர்வு செய்யப்படும் 1 லட்சம் மாணவர்களுக்கு ₹10,000 நேரடி பயனீட்டு பரிமாற்றம்.',
    'India\u2019s largest school-level science innovation programme, run by DST and NIF. Selected students (1 lakh a year) receive \u20b910,000 via Direct Benefit Transfer.',
    [
      { ta: 'ஆசிரியர் பள்ளியின் சார்பில் மாணவர் யோசனைகளை INSPIRE போர்ட்டலில் (inspireawards-dst.gov.in) சமர்ப்பிக்கிறார்.', en: 'A teacher submits student ideas through the INSPIRE portal (inspireawards-dst.gov.in) on behalf of the school.' },
      { ta: 'தேர்வு செய்யப்பட்ட மாணவர்களுக்கு ₹10,000 நேரடியாக வங்கி கணக்கில் வரும்.', en: 'Selected students receive \u20b910,000 directly to their bank account.' },
      { ta: 'அந்த தொகையில் செயல்முறை மாதிரியை உருவாக்கி, மாவட்ட கண்காட்சியில் (டிசம்பர்–ஜனவரி) காட்சிப்படுத்துங்கள்.', en: 'Use the grant to build a working prototype, then exhibit at the district fair (December\u2013January).' },
      { ta: 'மாவட்டம் → மாநிலம் (பிப்ரவரி) → தேசியம் (மார்ச்) → FINE, ராஷ்ட்ரபதி பவன்.', en: 'District \u2192 State (February) \u2192 National (March) \u2192 FINE at Rashtrapati Bhavan.' },
    ],
    'inspireawards-dst.gov.in',
    'DST + NIF, இந்திய அரசு', 'DST + NIF, Government of India',
    '2011',
    '~5 லட்சம் பள்ளிகள் (~34%)', '~5 lakh schools (~34% of India)',
    'சிறந்த மாணவர்கள் ஜப்பான் Sakura Science நிகழ்ச்சிக்கு', 'Top students nominated for Japan\u2019s Sakura Science High School Program',
    'அரசு மற்றும் தனியார்', 'Both government and private'
  ),
  C('rbvp', 'govt', 'upcoming',
    'RBVP / JNNSMEE', 'RBVP / JNNSMEE',
    'RBVP', 'RBVP',
    '6–12 வகுப்பு', 'Classes 6\u201312',
    'இலவசம்', 'Free',
    '2026-09-15', 'மாவட்ட கண்காட்சி', 'District exhibition',
    'ராஷ்ட்ரிய பால் வைக்ஞானிக் பிரதர்ஷனி. NCERT நடத்தும் இந்தியாவின் தொன்மையான தொடர் பள்ளி அறிவியல் கண்காட்சி (1971 முதல்). அனைத்து வாரியங்களுக்கும் திறந்தது.',
    'Rashtriya Bal Vaigyanik Pradarshani \u2014 India\u2019s oldest continuous school science exhibition, run by NCERT since 1971. Open to every school board.',
    [
      { ta: 'தமிழ்நாட்டில் SCERT மூலம் மாவட்ட கண்காட்சியில் பதிவு செய்யுங்கள் (செப்டம்பர்–அக்டோபர்).', en: 'In Tamil Nadu, register through SCERT for the district exhibition (September\u2013October).' },
      { ta: 'NCERT ஆண்டுதோறும் ஒரு கருவாக்கை அறிவிக்கும் — கணிதம், அறிவியல், சுற்றுச்சூழல், தொழில்நுட்பம் ஆகியவற்றில்.', en: 'NCERT announces an annual theme \u2014 across Maths, Science, Environment, or Technology.' },
      { ta: 'மாவட்டம் → மாநிலம் (அக்டோபர்–நவம்பர்) → தேசியம் (நவம்பர்–பிப்ரவரி).', en: 'District \u2192 State (Oct\u2013Nov) \u2192 National (Nov\u2013Feb).' },
      { ta: 'வெற்றியாளர்கள் IRIS National Fair-க்கு தேர்வு → அங்கிருந்து Regeneron ISEF (USA).', en: 'Winners are picked for the IRIS National Fair \u2192 from there to Regeneron ISEF (USA).' },
    ],
    'ncert.nic.in/jn-national-science-exhibition.php',
    'NCERT, கல்வி அமைச்சகம்', 'NCERT, Ministry of Education',
    '1971',
    '~7 லட்சம் பள்ளிகள் (~47%)', '~7 lakh schools (~47% of India)',
    'IRIS → Regeneron ISEF, USA', 'IRIS \u2192 Regeneron ISEF, USA',
    'அனைத்து வாரியங்களும்', 'All boards (CBSE, ICSE, state)'
  ),
  C('ncsc', 'govt', 'open',
    'தேசிய குழந்தைகள் அறிவியல் மாநாடு (NCSC)', 'National Children\u2019s Science Congress (NCSC)',
    'NCSC', 'NCSC',
    'வயது 10–17 · 2–5 பேர் குழு', 'Age 10\u201317 \u00b7 groups of 2\u20135',
    'இலவசம்', 'Free',
    '2026-10-31', 'மாவட்ட மாநாடு', 'District congress',
    'இந்தியாவின் மிகவும் சமத்துவமான போட்டி. பள்ளிக்கு வெளியே உள்ள குழந்தைகளும் பங்கேற்கலாம். திட்டங்கள் உள்ளூர் சமூக பிரச்சனைகளை அறிவியல் முறையில் தீர்க்க வேண்டும். 1993 முதல்.',
    'India\u2019s most inclusive competition \u2014 open to out-of-school children too. Projects must address local community problems using scientific method. Running since 1993.',
    [
      { ta: 'ஒரு வழிகாட்டியுடன் 2–5 பேர் கொண்ட குழுவை உருவாக்குங்கள்.', en: 'Form a team of 2\u20135 children with one guide.' },
      { ta: 'ஜூன்–செப்டம்பரில் உள்ளூர் சமூக பிரச்சனை மீது கள ஆய்வு செய்யுங்கள்.', en: 'Do field research on a local community problem between June and September.' },
      { ta: 'அக்டோபர்–நவம்பரில் மாவட்ட மாநாடு → நவம்பரில் மாநிலம் → டிசம்பர் 27–31 தேசியம்.', en: 'District congress (Oct\u2013Nov) \u2192 State (Nov) \u2192 National (Dec 27\u201331).' },
      { ta: 'சிறந்த திட்டங்கள் ஜனவரியில் இந்திய அறிவியல் மாநாட்டில் (ISCA) வழங்கப்படும்.', en: 'Best projects are showcased at the Indian Science Congress (ISCA) in January.' },
    ],
    'ncsc.co.in',
    'NCSTC / DST', 'NCSTC / DST',
    '1993',
    '~2 லட்சம் பள்ளிகள் · 7–8 லட்சம் மாணவர்கள்', '~2 lakh schools \u00b7 7\u20138 lakh students',
    'இந்திய அறிவியல் மாநாடு (ISCA), ஜனவரி', 'Indian Science Congress (ISCA), January',
    'அரசு, தனியார், மற்றும் பள்ளி வெளி குழந்தைகள்', 'Government, private, and out-of-school children'
  ),
  C('atl-marathon', 'govt', 'upcoming',
    'ATL பள்ளி புதுமை மாரத்தான்', 'ATL School Innovation Marathon',
    'ATL', 'ATL',
    '6–12 வகுப்பு · 2–3 மாணவர்கள் + 1 வழிகாட்டி', 'Classes 6\u201312 \u00b7 2\u20133 students + 1 mentor',
    'இலவசம் (ATL ஆய்வக பள்ளிக்கு)', 'Free (for schools with an ATL)',
    '2026-09-20', 'பதிவு', 'Registration',
    'NITI Aayog-ஆல் நடத்தப்படும். ATL பள்ளிகள் மற்றும் ATL-அல்லாத பள்ளிகளுக்கும் திறந்தது. குழுக்கள் உண்மையான உலக பிரச்சினைக்கு இயங்கும் முன்மாதிரியை உருவாக்க வேண்டும். கிராமப்புற மற்றும் அரசு பள்ளிகளுக்கு சிறப்பு அங்கீகாரம்.',
    'Run by NITI Aayog. Open to ATL and non-ATL schools. Teams must build a working prototype for a real-world problem. Special recognition for rural and government-school teams.',
    [
      { ta: '2–3 மாணவர்கள் + 1 ஆசிரியர் வழிகாட்டி குழுவை உருவாக்குங்கள் (ஆகஸ்ட்–செப்டம்பர்).', en: 'Form a team of 2\u20133 students + 1 teacher mentor (Aug\u2013Sep).' },
      { ta: 'செப்டம்பர்–ஜனவரியில் வார வார்த்தக்கங்கள் மற்றும் முன்மாதிரி கட்டமைப்பு.', en: 'Weekly workshops and prototype-building, September to January.' },
      { ta: 'ஜனவரி–மார்ச் மதிப்பீடு. சிறந்த குழுக்களுக்கு முன்னணி நிறுவனங்களில் Internship.', en: 'Evaluation January\u2013March. Top teams get internships with leading corporates.' },
      { ta: 'மார்ச்–ஏப்ரல் இறுதி நிகழ்வு. 2024 சீசனில் 54,000+ பள்ளிகள் பங்கேற்றன.', en: 'Finale in March\u2013April. The 2024 season saw 54,000+ schools participate.' },
    ],
    'aim.gov.in',
    'AIM, NITI Aayog', 'AIM, NITI Aayog',
    '2017',
    '~54,000 பள்ளிகள் (2024)', '~54,000 schools (2024)',
    'Student Innovator Program, முன்னணி நிறுவனங்களில் Internship', 'Student Innovator Program \u00b7 internships with leading corporates',
    'அரசு மற்றும் தனியார்', 'Both government and private'
  ),
  C('cbse-expo', 'govt', 'upcoming',
    'CBSE தேசிய அறிவியல் கண்காட்சி', 'CBSE National Science Exhibition',
    'CBSE Expo', 'CBSE Expo',
    'CBSE-இணைப்பு பள்ளிகள் · 6–12 வகுப்பு', 'CBSE-affiliated schools \u00b7 Classes 6\u201312',
    'இலவசம்', 'Free',
    '2026-09-30', 'பள்ளி சுற்று', 'School round',
    'CBSE பள்ளிகளுக்கு மட்டுமே. IRIS → Regeneron ISEF-க்கு ஒரு முக்கிய ஊட்டு கால்வாய். தமிழ்நாட்டில் ~2,500 CBSE பள்ளிகள் தகுதி.',
    'Only for CBSE-affiliated schools. A key feeder pipeline to IRIS \u2192 Regeneron ISEF. Tamil Nadu has ~2,500 eligible CBSE schools.',
    [
      { ta: 'ஆகஸ்ட்–செப்டம்பர் பள்ளி சுற்று → அக்டோபர்–நவம்பர் பிராந்திய.', en: 'School round in Aug\u2013Sep \u2192 regional round Oct\u2013Nov.' },
      { ta: 'டிசம்பர்–ஜனவரி தேசிய இறுதி — 25 இறுதியாளர்கள்.', en: 'National finale Dec\u2013Jan \u2014 25 finalists selected.' },
      { ta: 'திட்டங்கள் அறிவியல் கொள்கை, புதுமை, சமூக பொருத்தம் மற்றும் வழங்கல் முறையில் மதிப்பிடப்படும்.', en: 'Projects judged on principle, innovation, social relevance, and presentation.' },
      { ta: '5 சிறந்த தேசிய பதிவுகள் IRIS National Fair-க்கு நாமினேஷன்.', en: 'Top 5 national entries are nominated to the IRIS National Fair.' },
    ],
    'cbse.gov.in',
    'CBSE, கல்வி அமைச்சகம்', 'CBSE, Ministry of Education',
    '2000s',
    '~26,000 CBSE பள்ளிகள் (~1.8%)', '~26,000 CBSE schools (~1.8%)',
    'IRIS → Regeneron ISEF, USA', 'IRIS \u2192 Regeneron ISEF, USA',
    'CBSE மட்டுமே', 'CBSE-affiliated only'
  ),
  C('teri-green', 'ngo', 'open',
    'கிரீன் ஒலிம்பியாட் — TERI', 'Green Olympiad \u2014 TERI',
    'TERI', 'TERI',
    '4–10 வகுப்பு', 'Classes 4\u201310',
    'ரூ.60–100 / மாணவர்', '\u20b960\u2013100 per student',
    '2026-08-20', 'பதிவு', 'Registration',
    'TERI (The Energy and Resources Institute) நடத்தும் சுற்றுச்சூழல், காலநிலை மாற்றம் மற்றும் நிலைத்தன்மை மீதான எழுத்து தேர்வு. 1999 முதல்.',
    'A written examination on environment, climate change, and sustainability, run by TERI since 1999.',
    [
      { ta: 'பள்ளி ஜூன்–ஆகஸ்ட்டில் TERI-வில் பதிவு செய்கிறது.', en: 'School registers with TERI between June and August.' },
      { ta: 'செப்டம்பர்–அக்டோபர் எழுத்துத் தேர்வு — பள்ளியிலேயே.', en: 'Written exam held at the school itself, September\u2013October.' },
      { ta: 'நவம்பர்–டிசம்பர் முடிவுகள் மற்றும் விருதுகள்.', en: 'Results and awards released November\u2013December.' },
      { ta: 'இளையோருக்கான தனி பிரிவு உள்ளது (Junior Green Olympiad).', en: 'A separate Junior category exists.' },
    ],
    'teri.res.in/greenitiatives',
    'TERI, புதுடில்லி', 'TERI, New Delhi',
    '1999',
    '~4,000–6,000 பள்ளிகள்', '~4,000\u20136,000 schools',
    'சர்வதேச நுழைவாயில் இல்லை', 'No international gateway',
    'கட்டண அடிப்படையில் · பெரும்பாலும் தனியார்/நகர்ப்புற', 'Fee-based \u00b7 mostly private/urban'
  ),
  C('nse-ino', 'olympiad', 'upcoming',
    'NSE / INO — அறிவியல் ஒலிம்பியாட்', 'NSE / INO \u2014 Science Olympiad',
    'NSE/INO', 'NSE/INO',
    '12 வகுப்பு வரை · இந்திய பாஸ்போர்ட்', 'Up to Class 12 \u00b7 Indian passport',
    'குறைந்த தேர்வு கட்டணம்', 'Minimal exam fee',
    '2026-09-15', 'பதிவு முடிவு', 'Enrollment close',
    'இந்தியாவின் உண்மையான சர்வதேச ஒலிம்பியாட் பாதை. HBCSE/IAPT நடத்துகிறது. 5-நிலை குழாய் — NSE → INO → OCSC → சர்வதேச ஒலிம்பியாட் (IPhO, IChO, IBO, IOAA, IJSO).',
    'India\u2019s true international Olympiad pipeline, run by HBCSE and IAPT. A 5-stage funnel \u2014 NSE \u2192 INO \u2192 OCSC \u2192 international Olympiads (IPhO, IChO, IBO, IOAA, IJSO).',
    [
      { ta: 'ஆகஸ்ட்–செப்டம்பரில் உங்கள் பள்ளி NSE மையமாக பதிவு செய்யும் (குறைந்தது 20 மாணவர்கள்).', en: 'Your school registers as an NSE centre in Aug\u2013Sep (minimum 20 enrolling students).' },
      { ta: 'நவம்பர்: NSE தேர்வு — நிலை 1.', en: 'November: NSE exam \u2014 Stage 1.' },
      { ta: 'ஜனவரி: INO — நிலை 2 (~ஒவ்வொரு பாடத்திலும் 300 பேர்).', en: 'January: INO \u2014 Stage 2 (\u2248300 students per subject).' },
      { ta: 'ஏப்ரல்–ஜூன்: OCSC பயிற்சி முகாம் — 35 பேர். ஜூன்–ஜூலை: சர்வதேச ஒலிம்பியாட் (4–6 பேர்).', en: 'Apr\u2013Jun: OCSC training camp \u2014 35 students. Jun\u2013Jul: international Olympiad (4\u20136 students).' },
    ],
    'olympiads.hbcse.tifr.res.in',
    'HBCSE, TIFR · IAPT · DAE/DST/ISRO', 'HBCSE, TIFR \u00b7 IAPT \u00b7 DAE/DST/ISRO',
    '1987',
    '~1,400 NSE மையங்கள் (~0.1%)', '~1,400 NSE centres (~0.1%)',
    'IPhO · IChO · IBO · IOAA · IJSO', 'IPhO \u00b7 IChO \u00b7 IBO \u00b7 IOAA \u00b7 IJSO',
    'அரசு மற்றும் தனியார் (தகுதி அடிப்படையில்)', 'Both (merit-based centres)'
  ),
  C('sof-nso', 'private', 'soon',
    'SOF தேசிய அறிவியல் ஒலிம்பியாட் (NSO)', 'SOF National Science Olympiad (NSO)',
    'SOF NSO', 'SOF NSO',
    '1–12 வகுப்பு · பள்ளி வழியாக மட்டும்', 'Classes 1\u201312 \u00b7 only through school',
    'ரூ.125 / மாணவர்', '\u20b9125 per student',
    '2026-05-15', 'பதிவு', 'Registration',
    'தனியார் வணிக அமைப்பான Science Olympiad Foundation நடத்துகிறது. அரசு ஒலிம்பியாட் திட்டத்துடன் தொடர்பு இல்லை. HBCSE இதை தவறான சித்தரிப்பு என்று குறிப்பிட்டுள்ளது. ஆனால் பங்கேற்பில் மிகப்பெரியது (~50 லட்சம் மாணவர்கள்).',
    'Run by the private Science Olympiad Foundation. Not connected to the official government Olympiad pipeline \u2014 HBCSE has publicly called this a misrepresentation. Still the largest by participation (~5 million students).',
    [
      { ta: 'பள்ளி ஒருங்கிணைப்பாளர் SOF-ல் பதிவு செய்கிறார் (ஜூன்–செப்டம்பர்).', en: 'School coordinator registers with SOF (June\u2013September).' },
      { ta: 'அக்டோபர்–டிசம்பர்: நிலை 1 தேர்வு — பள்ளியிலேயே.', en: 'October\u2013December: Level 1 exam, held at the school itself.' },
      { ta: 'ஜனவரி–பிப்ரவரி: நிலை 2 — சுமார் 5% மாணவர்கள் தகுதி பெறுகின்றனர்.', en: 'January\u2013February: Level 2 \u2014 about 5% of students qualify.' },
      { ta: 'மார்ச்: முடிவுகள், பரிசுகள், சான்றிதழ்கள்.', en: 'March: results, medals, and certificates.' },
    ],
    'sofworld.org',
    'Science Olympiad Foundation (SOF)', 'Science Olympiad Foundation (SOF)',
    '1998',
    '~60,000–70,000 இந்திய பள்ளிகள்', '~60,000\u201370,000 Indian schools',
    'சர்வதேச ஒலிம்பியாட் நுழைவாயில் இல்லை', 'Not a gateway to IPhO/IChO/IBO',
    'அரசு மற்றும் தனியார் (பெரும்பாலும் தனியார்)', 'Both (predominantly private)'
  ),
  C('ico', 'olympiad', 'upcoming',
    'இந்திய கணினி ஒலிம்பியாட் (ICO)', 'Indian Computing Olympiad (ICO)',
    'ICO', 'ICO',
    '12 வகுப்பு வரை · அனைத்து வாரியங்கள்', 'Up to Class 12 \u00b7 all boards',
    'குறைந்தது', 'Minimal',
    '2026-11-15', 'ZIO (மண்டல சுற்று)', 'ZIO (zonal round)',
    'IARCS நடத்தும் அல்காரிதம் சிந்தனை மற்றும் போட்டி நிரலாக்க ஒலிம்பியாட். எந்த நிரலாக்க மொழியையும் பயன்படுத்தலாம். IOI-க்கு (சர்வதேச தகவல் ஒலிம்பியாட்) நேரடி பாதை.',
    'Algorithmic thinking and competitive programming Olympiad, run by IARCS. Students may use any programming language. Direct route to IOI (International Olympiad in Informatics).',
    [
      { ta: 'அக்டோபர்–நவம்பர்: ZIO (மண்டல சுற்று) — பதிவாக்கப்பட்ட மையங்களில்.', en: 'Oct\u2013Nov: ZIO (zonal round) at registered centres.' },
      { ta: 'ஜனவரி: IOQI (Indian Olympiad Qualifier for Informatics).', en: 'January: IOQI (Indian Olympiad Qualifier for Informatics).' },
      { ta: 'மே–ஜூன்: IOITC பயிற்சி முகாம் — இந்திய குழு தேர்வு.', en: 'May\u2013Jun: IOITC training camp \u2014 Indian team is selected here.' },
      { ta: 'ஜூலை: IOI சர்வதேசம் — 4 மாணவர்கள் இந்தியாவை பிரதிநிதித்துவம் செய்கின்றனர்.', en: 'July: IOI International \u2014 4 students represent India.' },
    ],
    'iarcs.org.in/inoi',
    'IARCS · HBCSE', 'IARCS \u00b7 HBCSE',
    '2000s',
    '~3,000 பள்ளிகள்', '~3,000 schools',
    'IOI (International Olympiad in Informatics)', 'IOI (International Olympiad in Informatics)',
    'அரசு மற்றும் தனியார்', 'Both (predominantly private/urban)'
  ),
  C('iris', 'ngo', 'soon',
    'IRIS National Fair', 'IRIS National Fair',
    'IRIS', 'IRIS',
    '5–12 வகுப்பு · 2 பேர் குழு வரை · இந்திய பள்ளிகள்', 'Classes 5\u201312 \u00b7 up to 2 per team \u00b7 Indian schools',
    'இலவசம் (விண்ணப்பம்)', 'Free (application)',
    '2026-10-15', 'விண்ணப்ப முடிவு', 'Application close',
    'இந்தியாவின் ISEF நுழைவாயில். EXSTEMPLAR + DST + Broadcom Foundation. உண்மையான ஆராய்ச்சி அல்லது புதுமை பொறியியல் திட்டங்கள் மட்டுமே — பாடப்புத்தக சோதனைகள் அல்ல.',
    'India\u2019s gateway to ISEF. Run by EXSTEMPLAR with DST and Broadcom Foundation. Only original research or novel engineering projects \u2014 textbook experiments are rejected.',
    [
      { ta: 'செப்டம்பர்–அக்டோபர்: விண்ணப்பங்கள் சமர்ப்பிக்கவும். 21 அறிவியல் பிரிவுகள்.', en: 'Sep\u2013Oct: submit applications across 21 science categories.' },
      { ta: 'நவம்பர்–டிசம்பர்: திரையிடல்.', en: 'Nov\u2013Dec: screening.' },
      { ta: 'ஜனவரி–பிப்ரவரி: தேசிய விழா — 100 இறுதியாளர்கள்.', en: 'Jan\u2013Feb: National fair \u2014 100 finalists.' },
      { ta: 'மே: சிறந்த குழுக்கள் Regeneron ISEF (அமெரிக்கா). இந்தியா இதுவரை 160 விருதுகள் வென்றுள்ளது.', en: 'May: top teams go to Regeneron ISEF (USA). India has won 160 ISEF awards to date.' },
    ],
    'irisnationalfair.org',
    'EXSTEMPLAR · DST · Broadcom Foundation', 'EXSTEMPLAR \u00b7 DST \u00b7 Broadcom Foundation',
    '1999',
    '~5,000 பள்ளிகள்', '~5,000 schools',
    'Regeneron ISEF — உலகின் மிகப்பெரிய பள்ளி அறிவியல் விழா', 'Regeneron ISEF \u2014 the world\u2019s largest pre-college science fair',
    'அரசு மற்றும் தனியார் (2019 முதல் அரசு சேர்ப்பு முன்முயற்சி)', 'Both (government-school inclusion push since 2019)'
  ),
  C('wro', 'robotics', 'upcoming',
    'உலக ரோபோட் ஒலிம்பியாட் — இந்தியா', 'World Robot Olympiad \u2014 India',
    'WRO', 'WRO',
    'வயது 8–19 · 2–3 பேர் குழு', 'Age 8\u201319 \u00b7 teams of 2\u20133',
    'ரூ.6,000–18,000 / குழு', '\u20b96,000\u201318,000 per team',
    '2026-10-31', 'மெய்நிகர் சுற்று', 'Virtual round',
    'India STEM Foundation + NCSM நடத்துகிறது. 4 சவால் பாதைகள் — RoboMission, Future Innovators, RoboSports, Future Engineers. கட்டணத் தடை காரணமாக பெரும்பாலும் நகர்ப்புற/தனியார்.',
    'Run by India STEM Foundation with NCSM. Four challenge tracks \u2014 RoboMission, Future Innovators, RoboSports, Future Engineers. The fee barrier keeps this mostly urban and private.',
    [
      { ta: 'நவம்பர்–டிசம்பர் மெய்நிகர் சுற்று.', en: 'November\u2013December: virtual round.' },
      { ta: 'ஜனவரி–பிப்ரவரி பிராந்திய சுற்று → மார்ச் தேசியம்.', en: 'Jan\u2013Feb: regionals \u2192 March: nationals.' },
      { ta: 'அக்டோபர்–நவம்பர்: WRO சர்வதேச சாம்பியன்ஷிப் — 90+ நாடுகள்.', en: 'Oct\u2013Nov: WRO International Championship \u2014 90+ countries.' },
      { ta: 'இந்தியா 2016ல் WRO சர்வதேச விழாவை நடத்தியது.', en: 'India hosted WRO International in 2016.' },
    ],
    'wroindia.org',
    'India STEM Foundation + NCSM', 'India STEM Foundation + NCSM',
    '2006',
    '~800 பள்ளிகள் · 1,000+ குழுக்கள் (2023)', '~800 schools \u00b7 1,000+ teams (2023)',
    'WRO International Championship (90+ நாடுகள்)', 'WRO International Championship (90+ countries)',
    'கட்டண அடிப்படையில் · பெரும்பாலும் நகர்/தனியார்', 'Fee-based \u00b7 mostly urban/private'
  ),
  C('fll', 'robotics', 'upcoming',
    'FIRST LEGO League — India', 'FIRST LEGO League \u2014 India',
    'FLL', 'FLL',
    'வயது 4–16 · 3 பிரிவுகள் · 10 பேர் வரை', 'Age 4\u201316 \u00b7 3 divisions \u00b7 up to 10 per team',
    'அதிகம் (கிட்கள் ரூ.15,000+ + கட்டணம்)', 'High (kits \u20b915,000+ plus fees)',
    '2026-09-30', 'சீசன் பதிவு', 'Season registration',
    'India STEM Foundation FIRST (USA) தேசிய கூட்டாளர். LEGO Education தொழில்நுட்ப கூட்டாளர். பட்டியலிட்ட அனைத்து போட்டிகளிலும் மிக அதிக செலவு தடை.',
    'India STEM Foundation is the national partner for FIRST (USA). LEGO Education is the technology partner. The highest cost barrier of all twelve competitions listed here.',
    [
      { ta: 'ஆகஸ்ட்: சீசன் துவக்கம். குழு உருவாக்கம் (ஆகஸ்ட்–அக்டோபர்).', en: 'August: season launch. Team formation (Aug\u2013Oct).' },
      { ta: 'நவம்பர்–ஜனவரி: ரோபோட் பயிற்சி + புதுமை திட்டம்.', en: 'Nov\u2013Jan: robot practice + innovation project.' },
      { ta: 'ஜனவரி–பிப்ரவரி: பிராந்திய / தேசிய சுற்றுகள்.', en: 'Jan\u2013Feb: regional and national rounds.' },
      { ta: 'ஏப்ரல்–மே: FIRST LEGO League World Festival (அமெரிக்கா).', en: 'Apr\u2013May: FIRST LEGO League World Festival (USA).' },
    ],
    'firstlegoleagueindia.org',
    'India STEM Foundation · FIRST · LEGO Education', 'India STEM Foundation \u00b7 FIRST \u00b7 LEGO Education',
    '2009',
    '~300–500 பள்ளிகள்', '~300\u2013500 schools',
    'FIRST LEGO League World Festival, USA (110+ நாடுகள்)', 'FIRST LEGO League World Festival, USA (110+ countries)',
    'முக்கியமாக நகர்ப்புற தனியார்', 'Predominantly urban private'
  ),
];

window.COPY = COPY;
window.COMPETITIONS = COMPETITIONS;
window.LAST_VERIFIED = LAST_VERIFIED;

// ------- Phase-by-phase academic-year timeline per competition -------
// Each phase: { level, title, note, months }.
//   level:   'registration' | 'district' | 'state' | 'national' | 'international'
//   months:  array of calendar month numbers (0=Jan..11=Dec) the phase occupies.
// The timeline UI grids these onto a Jun→May academic year.

const PHASES = {
  'inspire-manak': [
    { level: 'registration',  title: { ta: 'யோசனை சமர்ப்பணம்', en: 'Idea submission' },
      note:  { ta: 'ஆசிரியர் பள்ளி சார்பாக', en: 'Teacher on behalf of school' },
      months: [6, 7, 8, 9] },
    { level: 'district',      title: { ta: 'DLEPC — மாவட்ட கண்காட்சி', en: 'District exhibition' },
      note:  { ta: '₹10,000 DBT · முன்மாதிரி', en: '₹10,000 DBT · prototype' },
      months: [11, 0] },
    { level: 'state',         title: { ta: 'SLEPC — மாநிலம்', en: 'State exhibition' },
      note:  { ta: 'சிறந்த 10%', en: 'Top 10% advance' }, months: [1] },
    { level: 'national',      title: { ta: 'NLEPC + FINE', en: 'National + FINE' },
      note:  { ta: 'ராஷ்ட்ரபதி பவன்', en: 'At Rashtrapati Bhavan' }, months: [2, 3] },
    { level: 'international', title: { ta: 'Sakura · ஜப்பான்', en: 'Sakura · Japan' },
      note:  { ta: 'Top students nominated', en: 'Top students nominated' }, months: [4] },
  ],
  'rbvp': [
    { level: 'registration', title: { ta: 'பள்ளி பதிவு', en: 'School registration' },
      note:  { ta: 'SCERT வழியாக', en: 'Via SCERT' }, months: [6, 7, 8] },
    { level: 'district',     title: { ta: 'மாவட்ட கண்காட்சி', en: 'District exhibition' },
      months: [8, 9] },
    { level: 'state',        title: { ta: 'மாநில சுற்று', en: 'State round' },
      months: [9, 10] },
    { level: 'national',     title: { ta: 'JNNSMEE — தேசியம்', en: 'JNNSMEE — National' },
      months: [10, 11, 0, 1] },
    { level: 'international',title: { ta: 'IRIS → ISEF (USA)', en: 'IRIS → ISEF (USA)' },
      note:  { ta: 'வெற்றியாளர்களுக்கு', en: 'For winners only' }, months: [4] },
  ],
  'ncsc': [
    { level: 'registration', title: { ta: 'குழு + கள ஆய்வு', en: 'Team + fieldwork' },
      note:  { ta: '2–5 பேர் + வழிகாட்டி', en: '2–5 children + guide' }, months: [5, 6, 7, 8] },
    { level: 'district',     title: { ta: 'மாவட்ட மாநாடு', en: 'District congress' },
      months: [9, 10] },
    { level: 'state',        title: { ta: 'மாநில மாநாடு', en: 'State congress' },
      months: [10] },
    { level: 'national',     title: { ta: 'தேசிய மாநாடு', en: 'National congress' },
      note:  { ta: 'டிசம்பர் 27–31', en: 'Dec 27–31' }, months: [11] },
    { level: 'international',title: { ta: 'ISCA காட்சிப்படுத்தல்', en: 'ISCA showcase' },
      months: [0] },
  ],
  'atl-marathon': [
    { level: 'registration', title: { ta: 'குழு உருவாக்கம்', en: 'Team formation' },
      note:  { ta: '2–3 மாணவர் + வழிகாட்டி', en: '2–3 students + mentor' }, months: [7, 8] },
    { level: 'district',     title: { ta: 'வார்த்தக்கங்கள் + முன்மாதிரி', en: 'Workshops + prototype' },
      months: [8, 9, 10, 11, 0] },
    { level: 'national',     title: { ta: 'தேசிய மதிப்பீடு', en: 'National evaluation' },
      note:  { ta: 'Internship offers', en: 'Internship offers' }, months: [0, 1, 2] },
    { level: 'international',title: { ta: 'இறுதி நிகழ்வு', en: 'Finale' },
      months: [2, 3] },
  ],
  'cbse-expo': [
    { level: 'registration', title: { ta: 'பள்ளி சுற்று', en: 'School round' },
      note:  { ta: 'CBSE பள்ளிகள் மட்டுமே', en: 'CBSE schools only' }, months: [7, 8] },
    { level: 'district',     title: { ta: 'பிராந்திய சுற்று', en: 'Regional round' },
      months: [9, 10] },
    { level: 'national',     title: { ta: 'தேசிய இறுதி', en: 'National finale' },
      note:  { ta: '25 இறுதியாளர்கள்', en: '25 finalists' }, months: [11, 0] },
    { level: 'international',title: { ta: 'IRIS → ISEF', en: 'IRIS → ISEF' },
      months: [4] },
  ],
  'teri-green': [
    { level: 'registration', title: { ta: 'TERI-வில் பதிவு', en: 'Register with TERI' },
      months: [5, 6, 7] },
    { level: 'national',     title: { ta: 'எழுத்துத் தேர்வு', en: 'Written exam' },
      note:  { ta: 'பள்ளியிலேயே', en: 'At school itself' }, months: [8, 9] },
    { level: 'state',        title: { ta: 'முடிவுகள் + விருதுகள்', en: 'Results + awards' },
      months: [10, 11] },
  ],
  'nse-ino': [
    { level: 'registration', title: { ta: 'NSE மைய பதிவு', en: 'NSE centre enrollment' },
      note:  { ta: '≥20 மாணவர்கள்', en: '≥20 students' }, months: [7, 8] },
    { level: 'national',     title: { ta: 'NSE — நிலை 1', en: 'NSE — Stage 1' },
      months: [10] },
    { level: 'national',     title: { ta: 'INO — நிலை 2', en: 'INO — Stage 2' },
      note:  { ta: '≈300 ஒவ்வொரு பாடத்திலும்', en: '≈300 per subject' }, months: [0] },
    { level: 'national',     title: { ta: 'OCSC பயிற்சி முகாம்', en: 'OCSC training camp' },
      months: [3, 4, 5] },
    { level: 'international',title: { ta: 'IPhO · IChO · IBO · IOAA · IJSO', en: 'IPhO · IChO · IBO · IOAA · IJSO' },
      note:  { ta: '4–6 மாணவர்கள்', en: '4–6 students represent India' }, months: [5, 6] },
  ],
  'sof-nso': [
    { level: 'registration', title: { ta: 'பள்ளி ஒருங்கிணைப்பாளர் பதிவு', en: 'School coordinator registers' },
      months: [5, 6, 7, 8] },
    { level: 'national',     title: { ta: 'நிலை 1 — பள்ளியில்', en: 'Level 1 — at school' },
      months: [9, 10, 11] },
    { level: 'national',     title: { ta: 'நிலை 2', en: 'Level 2' },
      note:  { ta: 'சிறந்த ~5%', en: 'Top ~5% qualify' }, months: [0, 1] },
    { level: 'state',        title: { ta: 'முடிவுகள் + பதக்கங்கள்', en: 'Results + medals' },
      months: [2] },
  ],
  'ico': [
    { level: 'registration', title: { ta: 'ZIO — மண்டல சுற்று', en: 'ZIO — zonal round' },
      note:  { ta: 'பதிவு செய்த மையங்களில்', en: 'At registered centres' }, months: [9, 10] },
    { level: 'national',     title: { ta: 'IOQI தகுதி', en: 'IOQI qualifier' },
      months: [0] },
    { level: 'national',     title: { ta: 'IOITC பயிற்சி முகாம்', en: 'IOITC camp' },
      note:  { ta: 'இந்திய குழு தேர்வு', en: 'Indian team selected' }, months: [4, 5] },
    { level: 'international',title: { ta: 'IOI — சர்வதேசம்', en: 'IOI — International' },
      note:  { ta: '4 மாணவர்கள்', en: '4 students represent India' }, months: [6] },
  ],
  'iris': [
    { level: 'registration', title: { ta: 'விண்ணப்பம் — 21 பிரிவுகள்', en: 'Applications — 21 categories' },
      months: [8, 9] },
    { level: 'national',     title: { ta: 'திரையிடல்', en: 'Screening' },
      months: [10, 11] },
    { level: 'national',     title: { ta: 'தேசிய விழா — 100 இறுதி', en: 'National fair — 100 finalists' },
      months: [0, 1] },
    { level: 'international',title: { ta: 'Regeneron ISEF (USA)', en: 'Regeneron ISEF (USA)' },
      note:  { ta: 'உலகின் பெரிய விழா', en: 'World\u2019s largest fair' }, months: [4] },
  ],
  'wro': [
    { level: 'registration', title: { ta: 'குழு பதிவு', en: 'Team registration' },
      note:  { ta: '4 சவால் பாதைகள்', en: '4 challenge tracks' }, months: [7, 8, 9] },
    { level: 'district',     title: { ta: 'மெய்நிகர் சுற்று', en: 'Virtual round' },
      months: [10, 11] },
    { level: 'state',        title: { ta: 'பிராந்திய சுற்று', en: 'Regional round' },
      months: [0, 1] },
    { level: 'national',     title: { ta: 'தேசியம்', en: 'Nationals' },
      months: [2] },
    { level: 'international',title: { ta: 'WRO சர்வதேசம் (90+ நாடுகள்)', en: 'WRO International (90+ countries)' },
      months: [9, 10] },
  ],
  'fll': [
    { level: 'registration', title: { ta: 'சீசன் பதிவு · குழு உருவாக்கம்', en: 'Season registration · team formation' },
      months: [7, 8, 9] },
    { level: 'district',     title: { ta: 'ரோபோட் பயிற்சி + புதுமை', en: 'Robot practice + innovation' },
      months: [10, 11, 0] },
    { level: 'national',     title: { ta: 'பிராந்திய + தேசியம்', en: 'Regional + National' },
      months: [0, 1] },
    { level: 'international',title: { ta: 'FLL World Festival, USA', en: 'FLL World Festival, USA' },
      note:  { ta: '110+ நாடுகள்', en: '110+ countries' }, months: [3, 4] },
  ],
};

window.PHASES = PHASES;

// ------- Tamil Nadu participation data (by competition id) -------
// Placeholder-but-realistic figures; swap for verified data as it becomes
// available. "schools" and "districts" are 2024–25 academic year unless noted.
// `examples` are grouped by TN district; 2–6 real schools per district.
// `source` is a short, auditable line.

const TN_PARTICIPATION = {
  'inspire-manak': {
    schools: '~12,400',
    students: '~48,000',
    districts: 36,
    sourceLabel: { ta: 'SCERT தமிழ்நாடு · DST', en: 'SCERT Tamil Nadu · DST' },
    note: {
      ta: '2024–25ல் தமிழ்நாட்டிலிருந்து தேசிய நிலைக்கு தேர்வான 42 மாணவர்கள்.',
      en: '42 Tamil Nadu students selected to the national level in 2024–25.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['DAV Boys Senior Secondary, Gopalapuram', 'PSBB, Nungambakkam', 'Chettinad Vidyashram', 'Chennai Public School, Anna Nagar'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['PSG Sarvajana HSS', 'Suguna PIP School', 'Kumaraguru Matric HSS'] },
      { district: { ta: 'மதுரை', en: 'Madurai' }, schools: ['Velammal Vidhyashram', 'T.V.S. Lakshmi HSS', 'Sourashtra HSS'] },
      { district: { ta: 'திருச்சி', en: 'Tiruchirappalli' }, schools: ['Campion Anglo-Indian HSS', 'St. Joseph\u2019s HSS'] },
      { district: { ta: 'சேலம்', en: 'Salem' }, schools: ['Vidhya Sagar Global', 'Sri Vidya Mandir'] },
      { district: { ta: 'கன்யாகுமரி', en: 'Kanyakumari' }, schools: ['Vivekananda Vidyalaya', 'Carmel HSS, Nagercoil'] },
    ],
  },
  'rbvp': {
    schools: '~9,600',
    students: '~32,000',
    districts: 38,
    sourceLabel: { ta: 'SCERT தமிழ்நாடு · NCERT', en: 'SCERT Tamil Nadu · NCERT' },
    note: {
      ta: 'தமிழ்நாடு 2024ல் தேசிய கண்காட்சியில் 12 திட்டங்களை அனுப்பியது.',
      en: 'Tamil Nadu sent 12 projects to the national exhibition in 2024.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['Chennai High School, Saidapet', 'GHSS Triplicane', 'GGHSS Ashok Nagar'] },
      { district: { ta: 'ஈரோடு', en: 'Erode' }, schools: ['GHSS Perundurai', 'Gandhi Kalvi Nilayam'] },
      { district: { ta: 'திருநெல்வேலி', en: 'Tirunelveli' }, schools: ['St. Xavier\u2019s HSS', 'Sarah Tucker HSS'] },
      { district: { ta: 'தஞ்சாவூர்', en: 'Thanjavur' }, schools: ['Kalyanasundaram HSS', 'St. Antony\u2019s HSS'] },
    ],
  },
  'ncsc': {
    schools: '~15,200',
    students: '~62,000',
    districts: 38,
    sourceLabel: { ta: 'தமிழ்நாடு அறிவியல் பரிஷத் · DST', en: 'Tamil Nadu Science Forum · DST' },
    note: {
      ta: 'பள்ளிக்கு வெளியே உள்ள குழந்தைகள் உட்பட — மிகவும் விரிவான கலந்துகொள்ளல்.',
      en: 'Most inclusive participation — including out-of-school children.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['Chennai Middle School, Mylapore', 'PUMS Teynampet', 'GHSS Ambattur'] },
      { district: { ta: 'மதுரை', en: 'Madurai' }, schools: ['GHSS Melur', 'Lady Doak Matric HSS'] },
      { district: { ta: 'தூத்துக்குடி', en: 'Thoothukudi' }, schools: ['GHSS Kovilpatti', 'Caldwell HSS'] },
      { district: { ta: 'நாமக்கல்', en: 'Namakkal' }, schools: ['GHSS Rasipuram', 'Shanthi Matric HSS'] },
      { district: { ta: 'வேலூர்', en: 'Vellore' }, schools: ['Ida Scudder School', 'GHSS Gudiyatham'] },
    ],
  },
  'atl-marathon': {
    schools: '~3,800',
    students: '~14,000',
    districts: 32,
    sourceLabel: { ta: 'Atal Innovation Mission · NITI Aayog', en: 'Atal Innovation Mission · NITI Aayog' },
    note: {
      ta: '878 ATL ஆய்வகங்கள் தமிழ்நாட்டில் செயல்படுகின்றன (2024).',
      en: '878 active ATL labs across Tamil Nadu (2024).',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['Bhavan\u2019s Rajaji Vidyashram', 'DAV Adyar', 'PS Senior Secondary'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['Chinmaya Vidyalaya', 'Amrita Vidyalayam'] },
      { district: { ta: 'திருப்பூர்', en: 'Tiruppur' }, schools: ['Nehru Matric HSS', 'SNMV Matric HSS'] },
      { district: { ta: 'ஈரோடு', en: 'Erode' }, schools: ['Vellalar HSS', 'Nandha Central School'] },
    ],
  },
  'cbse-expo': {
    schools: '~1,200',
    students: '~3,400',
    districts: 18,
    sourceLabel: { ta: 'CBSE பிராந்திய அலுவலகம், சென்னை', en: 'CBSE Regional Office, Chennai' },
    note: {
      ta: 'தமிழ்நாட்டில் பெரும்பாலும் CBSE தனியார் பள்ளிகள் பங்கேற்கின்றன.',
      en: 'Participation in TN is largely from CBSE-affiliated private schools.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['DAV Gopalapuram', 'PSBB Senior Secondary', 'Vidya Mandir'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['Amrita Vidyalayam', 'Kendriya Vidyalaya CRPF'] },
      { district: { ta: 'சேலம்', en: 'Salem' }, schools: ['Shri Vidya Bharathi Matric', 'Golden Gates Matric'] },
    ],
  },
  'vvm': {
    schools: '~2,100',
    students: '~18,500',
    districts: 31,
    sourceLabel: { ta: 'Vijnana Bharati · Vigyan Prasar', en: 'Vijnana Bharati · Vigyan Prasar' },
    note: {
      ta: 'விஞ்ஞான் விஜ்ஞான் மஞ்சரி — இந்திய அறிவியல் வரலாறு சார்ந்த போட்டி.',
      en: 'Vidyarthi Vigyan Manthan — focused on Indian scientific heritage.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['Chettinad Hari Shree', 'Sindhi Model Senior Secondary'] },
      { district: { ta: 'திருச்சி', en: 'Tiruchirappalli' }, schools: ['Campion Anglo-Indian HSS', 'BHEL Matric HSS'] },
      { district: { ta: 'மதுரை', en: 'Madurai' }, schools: ['Velammal Vidhyashram', 'Dolphin School'] },
    ],
  },
  'nso': {
    schools: '~3,400',
    students: '~96,000',
    districts: 34,
    sourceLabel: { ta: 'Science Olympiad Foundation', en: 'Science Olympiad Foundation' },
    note: {
      ta: 'அதிக மாணவர்கள், ஆனால் கட்டணம் உண்டு (ரூ.125/மாணவர்).',
      en: 'High student count, but carries a per-student fee (~\u20b9125).',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['PSBB Main', 'Chettinad Vidyashram', 'Don Bosco Matric HSS'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['Kumarans Matric HSS', 'Stanes Anglo-Indian HSS'] },
      { district: { ta: 'மதுரை', en: 'Madurai' }, schools: ['Sri Sankara Vidyalaya', 'MSR Vidyalaya'] },
      { district: { ta: 'கடலூர்', en: 'Cuddalore' }, schools: ['St. Joseph\u2019s HSS', 'Little Flower Matric HSS'] },
    ],
  },
  'nstse': {
    schools: '~2,800',
    students: '~74,000',
    districts: 32,
    sourceLabel: { ta: 'Unified Council', en: 'Unified Council' },
    note: {
      ta: 'கருத்தாக்க-சார்ந்த தேர்வு. பல பள்ளிகள் NSO + NSTSE-ஐ இணைத்து நடத்துகின்றன.',
      en: 'Concept-based test. Many schools offer NSO and NSTSE together.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['PS Senior Secondary', 'Bhavan\u2019s Rajaji', 'DAV Mogappair'] },
      { district: { ta: 'திருநெல்வேலி', en: 'Tirunelveli' }, schools: ['St. Xavier\u2019s HSS', 'Rose Mary HSS'] },
      { district: { ta: 'திருப்பூர்', en: 'Tiruppur' }, schools: ['Nehru Matric HSS', 'Velammal Vidyalaya'] },
    ],
  },
  'kvpy': {
    schools: '~1,400',
    students: '~6,200',
    districts: 24,
    sourceLabel: { ta: 'IISc Bangalore · DST', en: 'IISc Bangalore · DST' },
    note: {
      ta: 'அதி-தேர்வு போட்டி — வலுவான அறிவியல் பின்னணி கொண்ட மாணவர்களுக்கு.',
      en: 'Highly selective — for students with a strong science background.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['PSBB Senior Secondary', 'DAV Gopalapuram', 'Vidya Mandir Mylapore'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['PSG Public Schools', 'Amrita Vidyalayam'] },
      { district: { ta: 'மதுரை', en: 'Madurai' }, schools: ['TVS Academy', 'Velammal Vidhyashram'] },
    ],
  },
  'iris': {
    schools: '~900',
    students: '~2,400',
    districts: 20,
    sourceLabel: { ta: 'IRIS National Fair · DST', en: 'IRIS National Fair · DST' },
    note: {
      ta: 'Regeneron ISEF (USA)-க்கு நேரடி வழி.',
      en: 'Direct path to Regeneron ISEF (USA).',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['Chettinad Vidyashram', 'DAV Gopalapuram'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['PSG Sarvajana HSS'] },
      { district: { ta: 'திருச்சி', en: 'Tiruchirappalli' }, schools: ['BHEL Matric HSS'] },
    ],
  },
  'wro': {
    schools: '~180',
    students: '~720',
    districts: 12,
    sourceLabel: { ta: 'India STEM Foundation', en: 'India STEM Foundation' },
    note: {
      ta: 'கட்டண அடிப்படையில் இயங்குகிறது — நகர்ப்புற தனியார் பள்ளிகள் அதிகம்.',
      en: 'Fee-based; urban/private schools dominate the TN cohort.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['PSBB Nungambakkam', 'Chettinad Hari Shree', 'Chinmaya Vidyalaya'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['PSG Public Schools', 'Suguna PIP'] },
    ],
  },
  'fll': {
    schools: '~90',
    students: '~420',
    districts: 8,
    sourceLabel: { ta: 'India STEM Foundation · FIRST', en: 'India STEM Foundation · FIRST' },
    note: {
      ta: 'அதிக செலவு தடை — பட்டியலிட்ட 12 போட்டிகளில் மிகவும் குறைந்த கலந்துகொள்ளல்.',
      en: 'Highest cost barrier — the lowest participation of all 12 listed.',
    },
    examples: [
      { district: { ta: 'சென்னை', en: 'Chennai' }, schools: ['PSBB Nungambakkam', 'American International School'] },
      { district: { ta: 'கோயம்புத்தூர்', en: 'Coimbatore' }, schools: ['PSG Public Schools'] },
    ],
  },
};

window.TN_PARTICIPATION = TN_PARTICIPATION;
